export const SpanAttributes = {
  CORRELATION_ID: 'app.correlation_id',
  CAUSATION_ID: 'app.causation_id',
  COMMAND_NAME: 'app.command.name',
  QUERY_NAME: 'app.query.name',
  EVENT_TYPE: 'app.event.type',
  AGGREGATE_TYPE: 'app.aggregate.type',
  AGGREGATE_ID: 'app.aggregate.id',
  REPOSITORY_ENTITY: 'app.repository.entity',
  REPOSITORY_OPERATION: 'app.repository.operation',
  JOB_QUEUE: 'app.job.queue',
  JOB_NAME: 'app.job.name',
  JOB_ID: 'app.job.id',
  JOB_ATTEMPT: 'app.job.attempt',
  OUTBOX_EVENT_TYPE: 'app.outbox.event_type',
  OUTBOX_AGGREGATE_TYPE: 'app.outbox.aggregate_type',
  HTTP_ROUTE: 'http.route',
  HTTP_METHOD: 'http.method',
  HTTP_STATUS_CODE: 'http.status_code',
  ACTOR_USER_ID: 'app.actor.user_id',
  ACTOR_STORE_ID: 'app.actor.store_id',
} as const;
