FROM node:22-alpine
WORKDIR /app
# Enable pnpm via Corepack
RUN corepack enable
#Copy only manifests first for better caching
COPY package.json pnpm-lock.yaml ./
# Install all dependencies (including dev)
RUN pnpm install --frozen-lockfile
# Copy entrypoint script
COPY /scripts/docker-entrypoint.dev.sh /entrypoint.sh
# Make entrypoint executable
RUN chmod +x /entrypoint.sh
# Get app name from argument (e.g. "worker-core")
ARG APP_NAME
# Set environment variable for app name (optional, can also be passed at runtime)
ENV APP_NAME=${APP_NAME}
# Start the app in development mode
ENTRYPOINT [ "/entrypoint.sh" ]