import { Kysely, sql } from 'kysely';

export async function up(db: Kysely<any>): Promise<void> {
  await sql
    .raw(
      `
-- Precomputed trends for products at different geographic scopes.
-- Generated by analytics worker from fact_sales (and optionally inventory movement facts).
-- Used by recommendation worker.

-- Geographic scope hierarchy used for trend fallback.
CREATE TYPE analytics.geo_scope AS ENUM ('store', 'local_area', 'city', 'state', 'country');

CREATE TYPE analytics.trend_granularity AS ENUM ('daily', 'weekly', 'bi_weekly', 'monthly', 'quarterly', 'yearly');

CREATE TABLE analytics.product_trend_snapshots (
  id UUID PRIMARY KEY DEFAULT uuidv7(),

  product_variant_id UUID NOT NULL,
  -- store_id is populated only when scope = 'store'
  -- For broader scopes (city, state, country) store_id is NULL
  -- because the snapshot aggregates across multiple stores
  store_id UUID,

  -- Scope identity
  scope analytics.geo_scope NOT NULL,
  scope_ref_id TEXT NOT NULL,  
  -- scope='store'      → store UUID as text e.g. 'uuid-of-store'
  -- scope='local_area' → area name e.g. 'surulere'
  -- scope='city'       → city name e.g. 'lagos'
  -- scope='state'      → state name e.g. 'lagos-state'
  -- scope='country'    → ISO code e.g. 'NG'

  -- Time window
  window_start DATE NOT NULL,
  -- window_end is EXCLUSIVE: a daily window for 2026-03-01 is window_start='2026-03-01', window_end='2026-03-02'
  window_end DATE NOT NULL,
  granularity analytics.trend_granularity NOT NULL DEFAULT 'daily',

  -- Metrics (keep these minimal but powerful)
  units_sold NUMERIC(19,6) NOT NULL DEFAULT 0,
  revenue NUMERIC(19,4) NOT NULL DEFAULT 0,
  orders_count INT NOT NULL DEFAULT 0,
  avg_unit_price NUMERIC(19,4),
  median_unit_price NUMERIC(19,4),
  sales_velocity NUMERIC(19,6), -- e.g. units/day in window

  data_points INT NOT NULL DEFAULT 0, -- number of line items contributing
  confidence_score NUMERIC(6,4) NOT NULL DEFAULT 0, -- 0..1

  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT chk_trends_metadata_object CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT chk_trends_window CHECK (window_end > window_start),
  CONSTRAINT chk_trends_confidence
    CHECK (confidence_score >= 0 AND confidence_score <= 1),
  CONSTRAINT chk_trends_store_scope_consistency
    CHECK (
      (scope = 'store' AND store_id IS NOT NULL)
      OR (scope <> 'store' AND store_id IS NULL)
    )
);

-- Indexes
CREATE UNIQUE INDEX ux_product_trends_scope_window
  ON analytics.product_trend_snapshots (
    product_variant_id, scope, scope_ref_id, window_start, window_end, granularity
  );

CREATE INDEX idx_product_trends_product_scope_window
  ON analytics.product_trend_snapshots (product_variant_id, scope, window_start DESC);

CREATE INDEX idx_product_trends_scope_ref_window
  ON analytics.product_trend_snapshots (scope, scope_ref_id, window_start DESC);

CREATE INDEX idx_product_trends_store_product_window
  ON analytics.product_trend_snapshots (store_id, product_variant_id, window_start DESC)
  WHERE store_id IS NOT NULL;
      `,
    )
    .execute(db);
}

export async function down(db: Kysely<any>): Promise<void> {
  await sql
    .raw(
      `
DROP TABLE IF EXISTS analytics.product_trend_snapshots;
DROP TYPE IF EXISTS analytics.geo_scope;
DROP TYPE IF EXISTS analytics.trend_granularity;
      `,
    )
    .execute(db);
}
