import { Kysely, sql } from 'kysely';

export async function up(db: Kysely<any>): Promise<void> {
  await sql
    .raw(
      `
-- Inventory reorder recommendations generated by recommendation worker.
-- Read by the app to show "Suggested restock" lists.

CREATE TYPE analytics.recommendation_status AS ENUM (
  'active',
  'dismissed',
  'applied',
  'expired'
);

CREATE TABLE analytics.inventory_recommendations (
  id UUID PRIMARY KEY DEFAULT uuidv7(),
  store_id UUID NOT NULL,
  business_id UUID,
  product_variant_id UUID NOT NULL,

  -- Recommendation
  recommended_quantity NUMERIC(19,6) NOT NULL,
  recommended_uom TEXT,               -- display hint; base is assumed unless set
  recommended_by_scope analytics.geo_scope NOT NULL DEFAULT 'store', -- scope used after fallback

  -- Why (explainability)
  window_start DATE NOT NULL,
  -- window_end is EXCLUSIVE, consistent with product_trend_snapshots convention
  window_end DATE NOT NULL,
  avg_daily_units NUMERIC(19,6),
  lead_time_days INT,                 -- if you later model supplier lead time
  safety_stock_units NUMERIC(19,6),
  confidence_score NUMERIC(6,4) NOT NULL DEFAULT 0, -- 0..1
  explanation JSONB NOT NULL DEFAULT '{}'::jsonb,    -- e.g., inputs used, fallback path, assumptions

  status analytics.recommendation_status NOT NULL DEFAULT 'active',
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ,

  dismissed_at TIMESTAMPTZ,
  dismissed_by_store_member_id UUID,

  applied_at TIMESTAMPTZ,
  applied_by_store_member_id UUID,
  applied_reference TEXT,             -- e.g. PO number created from recommendation (optional)

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT chk_inv_reco_explanation_object CHECK (jsonb_typeof(explanation) = 'object'),
  CONSTRAINT chk_inv_reco_confidence
    CHECK (confidence_score >= 0 AND confidence_score <= 1),
  CONSTRAINT chk_inv_reco_qty_positive CHECK (recommended_quantity > 0),
  CONSTRAINT chk_inv_reco_status_consistency
    CHECK (
      (status = 'active' AND dismissed_at IS NULL AND applied_at IS NULL)
      OR (status = 'dismissed' AND dismissed_at IS NOT NULL AND dismissed_by_store_member_id IS NOT NULL)
      OR (status = 'applied' AND applied_at IS NOT NULL AND applied_by_store_member_id IS NOT NULL)
      OR (status = 'expired' AND expires_at IS NOT NULL)
    )
);

-- Indexes
CREATE UNIQUE INDEX ux_inv_recos_store_variant_active
  ON analytics.inventory_recommendations (store_id, product_variant_id)
  WHERE status = 'active';

CREATE INDEX idx_inv_recos_store_status
  ON analytics.inventory_recommendations (store_id, status, generated_at DESC);

CREATE INDEX idx_inv_recos_store_product
  ON analytics.inventory_recommendations (store_id, product_variant_id, generated_at DESC);
      `,
    )
    .execute(db);
}

export async function down(db: Kysely<any>): Promise<void> {
  await sql
    .raw(
      `

      `,
    )
    .execute(db);
}
