/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type AnalyticsGeoScope = 'city' | 'country' | 'local_area' | 'state' | 'store';

export type AnalyticsRecommendationStatus = 'active' | 'applied' | 'dismissed' | 'expired';

export type AnalyticsRowIngestStatus = 'active' | 'retracted';

export type AnalyticsTrendGranularity =
  | 'bi_weekly'
  | 'daily'
  | 'monthly'
  | 'quarterly'
  | 'weekly'
  | 'yearly';

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[] ? U[] : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> =
  T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S[], I[], U[]> : T[];

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type OperationalAuditAction = 'delete' | 'insert' | 'restore' | 'soft_delete' | 'update';

export type OperationalAuditSource = 'api' | 'import' | 'migration' | 'pos' | 'system';

export type OperationalBarcodeStatus = 'active' | 'deprecated';

export type OperationalBarcodeType =
  | 'code_128'
  | 'code_39'
  | 'data_matrix'
  | 'ean_13'
  | 'ean_8'
  | 'other'
  | 'qr'
  | 'upc_a'
  | 'upc_e';

export type OperationalBillingCustomerStatus = 'active' | 'closed' | 'delinquent' | 'suspended';

export type OperationalBusinessStatus = 'active' | 'suspended';

export type OperationalDiscountConditionType =
  | 'member_role'
  | 'min_quantity'
  | 'min_transaction_amount'
  | 'specific_category'
  | 'specific_product'
  | 'specific_tax_class';

export type OperationalDiscountScope = 'line_item' | 'transaction';

export type OperationalDiscountType = 'fixed_amount' | 'percentage';

export type OperationalInventoryAdjustmentDirection = 'in' | 'out';

export type OperationalInventoryAdjustmentKind = 'manual_adjustment' | 'writeoff' | 'writeon';

export type OperationalInventoryAdjustmentReasonCategory =
  | 'correction'
  | 'damage'
  | 'expiry'
  | 'internal_use'
  | 'other'
  | 'shrinkage';

export type OperationalInventoryAdjustmentStatus =
  | 'approved'
  | 'cancelled'
  | 'draft'
  | 'posted'
  | 'submitted';

export type OperationalInventoryMovementDirection = 'in' | 'out';

export type OperationalInventoryMovementType =
  | 'adjustment'
  | 'customer_return'
  | 'opening_stock'
  | 'purchase'
  | 'sale'
  | 'supplier_return'
  | 'transfer';

export type OperationalInventorySerialStatus =
  | 'damaged'
  | 'in_stock'
  | 'returned'
  | 'sold'
  | 'written_off';

export type OperationalInventoryTransferStatus = 'cancelled' | 'completed' | 'draft' | 'submitted';

export type OperationalInvoiceStatus = 'draft' | 'issued' | 'paid' | 'uncollectible' | 'void';

export type OperationalLocationType =
  | 'aisle'
  | 'bay'
  | 'bin'
  | 'display'
  | 'other'
  | 'pallet_pos'
  | 'peg'
  | 'rack'
  | 'room'
  | 'shelf'
  | 'slot'
  | 'virtual'
  | 'zone';

export type OperationalMfaType = 'email' | 'totp';

export type OperationalNotificationAudienceType = 'member' | 'member_list' | 'role' | 'store';

export type OperationalNotificationChannel = 'email' | 'in_app';

export type OperationalNotificationDeliveryStatus = 'bounced' | 'failed' | 'pending' | 'sent';

export type OperationalNotificationStatus =
  | 'cancelled'
  | 'failed'
  | 'fanned_out'
  | 'queued'
  | 'sent';

export type OperationalOutboxDestination = 'bullmq';

export type OperationalOutboxEventStatus =
  | 'cancelled'
  | 'failed'
  | 'locked'
  | 'pending'
  | 'published';

export type OperationalPaymentStatus =
  | 'cancelled'
  | 'failed'
  | 'pending'
  | 'refunded'
  | 'succeeded';

export type OperationalPlanInterval = 'month' | 'year';

export type OperationalPosPaymentIntentStatus =
  | 'cancelled'
  | 'confirmed'
  | 'failed'
  | 'initiated'
  | 'pending';

export type OperationalPosPaymentIntentType = 'payment' | 'refund';

export type OperationalPosPaymentMethod =
  | 'bank_transfer'
  | 'card'
  | 'cash'
  | 'mixed'
  | 'mobile_money'
  | 'unknown';

export type OperationalPosSessionStatus = 'closed' | 'open';

export type OperationalPosTransactionStatus = 'completed' | 'held' | 'open' | 'voided';

export type OperationalPosTransactionType = 'return' | 'sale';

export type OperationalProductStatus = 'active' | 'archived' | 'inactive';

export type OperationalProductType = 'digital' | 'physical' | 'service';

export type OperationalProductUomUsage = 'both' | 'purchase' | 'sale';

export type OperationalPurchaseOrderStatus =
  | 'approved'
  | 'cancelled'
  | 'draft'
  | 'partially_received'
  | 'received'
  | 'sent'
  | 'submitted';

export type OperationalPurchaseReceiptStatus = 'cancelled' | 'draft' | 'posted';

export type OperationalQuantityMode = 'length' | 'unit' | 'volume' | 'weight';

export type OperationalReportOutputFormat = 'csv' | 'json' | 'pdf' | 'xlsx';

export type OperationalReportRunStatus =
  | 'cancelled'
  | 'completed'
  | 'failed'
  | 'queued'
  | 'running';

export type OperationalReportScope = 'analytics' | 'operational';

export type OperationalSequenceResetPolicy = 'daily' | 'monthly' | 'never' | 'yearly';

export type OperationalSequenceScope = 'store';

export type OperationalStocktakeStatus = 'cancelled' | 'completed' | 'draft' | 'in_progress';

export type OperationalStockValuationMethod =
  | 'fifo'
  | 'lifo'
  | 'standard_cost'
  | 'weighted_average';

export type OperationalStoreInvitationStatus = 'accepted' | 'expired' | 'pending' | 'revoked';

export type OperationalStoreMemberStatus = 'active' | 'suspended';

export type OperationalStoreRole = 'administrator' | 'attendant' | 'owner' | 'staff';

export type OperationalStoreStatus = 'active' | 'closed' | 'suspended';

export type OperationalSubscriptionStatus =
  | 'active'
  | 'cancelled'
  | 'expired'
  | 'past_due'
  | 'paused'
  | 'trialing';

export type OperationalSupplierReturnStatus =
  | 'approved'
  | 'cancelled'
  | 'completed'
  | 'draft'
  | 'shipped'
  | 'submitted';

export type OperationalTaxBase =
  | 'subtotal'
  | 'subtotal_plus_all_prior'
  | 'subtotal_plus_non_compound';

export type OperationalTaxScope = 'line_item' | 'order' | 'shipping';

export type OperationalUserStatus = 'active' | 'disabled';

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AnalyticsFactSales {
  attendant_store_member_id: string | null;
  barcode: string | null;
  business_id: string | null;
  category_id: string | null;
  category_label: string | null;
  created_at: Generated<Timestamp>;
  currency_code: string;
  event_id: string;
  event_occurred_at: Timestamp;
  event_type: string;
  id: Generated<string>;
  ingest_status: Generated<AnalyticsRowIngestStatus>;
  line_cost_total: Numeric | null;
  line_discount_amount: Generated<Numeric>;
  line_subtotal: Numeric;
  line_tax_amount: Generated<Numeric>;
  line_total: Numeric;
  location_id: string | null;
  metadata: Generated<Json>;
  payment_method: string | null;
  pos_line_item_id: string;
  pos_session_id: string | null;
  pos_transaction_id: string;
  product_cluster_id: string | null;
  product_name: string;
  quantity: Numeric;
  retracted_at: Timestamp | null;
  retraction_reason: string | null;
  sku: string | null;
  sold_at: Timestamp;
  sold_date: Timestamp;
  sold_hour: number;
  sold_month: number;
  sold_year: number;
  store_city: string | null;
  store_country_code: string | null;
  store_geo_location: string | null;
  store_id: string;
  store_local_area: string | null;
  store_product_id: string;
  store_state: string | null;
  terminal_id: string | null;
  unit_cost: Numeric | null;
  unit_price: Numeric;
}

export interface AnalyticsInventoryRecommendations {
  applied_at: Timestamp | null;
  applied_by_store_member_id: string | null;
  applied_reference: string | null;
  avg_daily_units: Numeric | null;
  business_id: string | null;
  confidence_score: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  dismissed_at: Timestamp | null;
  dismissed_by_store_member_id: string | null;
  expires_at: Timestamp | null;
  explanation: Generated<Json>;
  generated_at: Generated<Timestamp>;
  id: Generated<string>;
  lead_time_days: number | null;
  product_variant_id: string;
  recommended_by_scope: Generated<AnalyticsGeoScope>;
  recommended_quantity: Numeric;
  recommended_uom: string | null;
  safety_stock_units: Numeric | null;
  status: Generated<AnalyticsRecommendationStatus>;
  store_id: string;
  window_end: Timestamp;
  window_start: Timestamp;
}

export interface AnalyticsProductTrendSnapshots {
  avg_unit_price: Numeric | null;
  confidence_score: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  data_points: Generated<number>;
  granularity: Generated<AnalyticsTrendGranularity>;
  id: Generated<string>;
  median_unit_price: Numeric | null;
  metadata: Generated<Json>;
  orders_count: Generated<number>;
  product_variant_id: string;
  revenue: Generated<Numeric>;
  sales_velocity: Numeric | null;
  scope: AnalyticsGeoScope;
  scope_ref_id: string;
  store_id: string | null;
  units_sold: Generated<Numeric>;
  window_end: Timestamp;
  window_start: Timestamp;
}

export interface GeographyColumns {
  coord_dimension: number | null;
  f_geography_column: string | null;
  f_table_catalog: string | null;
  f_table_name: string | null;
  f_table_schema: string | null;
  srid: number | null;
  type: string | null;
}

export interface GeometryColumns {
  coord_dimension: number | null;
  f_geometry_column: string | null;
  f_table_catalog: string | null;
  f_table_name: string | null;
  f_table_schema: string | null;
  srid: number | null;
  type: string | null;
}

export interface OperationalAuditLogs {
  action: OperationalAuditAction;
  actor_store_member_id: string | null;
  actor_user_id: string | null;
  after_data: Json | null;
  before_data: Json | null;
  changed_fields: Generated<string[]>;
  correlation_id: string | null;
  created_at: Generated<Timestamp>;
  diff: Generated<Json>;
  entity_display: string | null;
  entity_id: string;
  entity_table: string;
  id: Generated<string>;
  idempotency_key: string | null;
  ip_address: string | null;
  reason: string | null;
  request_id: string | null;
  session_id: string | null;
  source: Generated<OperationalAuditSource>;
  store_id: string | null;
  terminal_id: string | null;
  user_agent: string | null;
}

export interface OperationalBarcodeRegistry {
  barcode: string;
  barcode_type: OperationalBarcodeType | null;
  confidence_score: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  first_seen_at: Timestamp | null;
  first_seen_store_id: string | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  observation_count: Generated<number>;
  status: Generated<OperationalBarcodeStatus>;
  suggested_brand: string | null;
  suggested_category: string | null;
  suggested_name: string | null;
  suggested_pack_size: string | null;
  updated_at: Timestamp | null;
}

export interface OperationalBillingCustomers {
  billing_address_line1: string | null;
  billing_address_line2: string | null;
  billing_city: string | null;
  billing_country_code: string | null;
  billing_email: string | null;
  billing_local_area: string | null;
  billing_phone: string | null;
  billing_postal_code: string | null;
  billing_state: string | null;
  business_id: string;
  created_at: Generated<Timestamp>;
  currency: string;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  provider_customer_ref: string | null;
  provider_name: string | null;
  status: Generated<OperationalBillingCustomerStatus>;
  timezone: string | null;
  updated_at: Timestamp | null;
}

export interface OperationalBillingInvoices {
  billing_customer_id: string;
  billing_period_end: Timestamp | null;
  billing_period_start: Timestamp | null;
  business_id: string;
  created_at: Generated<Timestamp>;
  currency: string;
  deleted_at: Timestamp | null;
  discount_amount: Generated<Numeric>;
  due_at: Timestamp | null;
  id: Generated<string>;
  invoice_number: string;
  issued_at: Generated<Timestamp>;
  metadata: Generated<Json>;
  paid_at: Timestamp | null;
  provider_invoice_ref: string | null;
  provider_name: string | null;
  status: Generated<OperationalInvoiceStatus>;
  subscription_id: string | null;
  subtotal_amount: Generated<Numeric>;
  tax_amount: Generated<Numeric>;
  total_amount: Generated<Numeric>;
  updated_at: Timestamp | null;
}

export interface OperationalBillingPaymentMethods {
  billing_customer_id: string;
  business_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  details: Generated<Json>;
  id: Generated<string>;
  is_default: Generated<boolean>;
  provider_authorization_ref: string;
  provider_name: string;
}

export interface OperationalBillingPayments {
  amount: Numeric;
  billing_customer_id: string;
  business_id: string;
  created_at: Generated<Timestamp>;
  currency: string;
  deleted_at: Timestamp | null;
  failed_at: Timestamp | null;
  failure_reason: string | null;
  id: Generated<string>;
  invoice_id: string | null;
  metadata: Generated<Json>;
  paid_at: Timestamp | null;
  payment_method: string | null;
  payment_method_id: string | null;
  payment_reference: string | null;
  provider_name: string | null;
  provider_payment_ref: string | null;
  status: Generated<OperationalPaymentStatus>;
  subscription_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalBillingPlans {
  code: string;
  created_at: Generated<Timestamp>;
  currency: string;
  deleted_at: Timestamp | null;
  description: string | null;
  entitlements: Generated<Json>;
  id: Generated<string>;
  interval: Generated<OperationalPlanInterval>;
  is_active: Generated<boolean>;
  name: string;
  price_amount: Numeric;
  sort_order: number | null;
  trial_days: Generated<number>;
  updated_at: Timestamp | null;
}

export interface OperationalBillingSubscriptionEvents {
  actor_store_member_id: string | null;
  business_id: string;
  created_at: Generated<Timestamp>;
  event_type: string;
  id: Generated<string>;
  invoice_id: string | null;
  metadata: Generated<Json>;
  payment_id: string | null;
  plan_id: string | null;
  subscription_id: string;
}

export interface OperationalBillingSubscriptions {
  billing_customer_id: string;
  business_id: string;
  cancel_at_period_end: Generated<boolean>;
  cancelled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  current_period_end: Timestamp | null;
  current_period_start: Timestamp | null;
  default_payment_method_id: string | null;
  deleted_at: Timestamp | null;
  features_snapshot: Generated<Json>;
  grace_period_ends_at: Timestamp | null;
  id: Generated<string>;
  limits_snapshot: Generated<Json>;
  metadata: Generated<Json>;
  plan_id: string;
  provider_name: string | null;
  provider_subscription_ref: string | null;
  status: Generated<OperationalSubscriptionStatus>;
  suspended_at: Timestamp | null;
  trial_ends_at: Timestamp | null;
  updated_at: Timestamp | null;
}

export interface OperationalBusinesses {
  address_extra: Json | null;
  address_line_1: string | null;
  address_line_2: string | null;
  city: string | null;
  country_code: string | null;
  created_at: Generated<Timestamp>;
  default_currency: Generated<string>;
  default_timezone: Generated<string>;
  deleted_at: Timestamp | null;
  geo_location: string | null;
  id: Generated<string>;
  legal_name: string;
  metadata: Generated<Json>;
  owned_by_user_id: string;
  postal_code: string | null;
  primary_email: string | null;
  primary_phone: string | null;
  primary_store_id: string | null;
  registration_number: string | null;
  state: string | null;
  status: Generated<OperationalBusinessStatus>;
  tax_id: string | null;
  trading_name: string | null;
  updated_at: Timestamp | null;
}

export interface OperationalInventoryAdjustmentLines {
  adjustment_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  direction: OperationalInventoryAdjustmentDirection;
  entered_quantity: Numeric | null;
  entered_uom_id: string | null;
  id: Generated<string>;
  line_value: Numeric | null;
  location_id: string | null;
  lot_id: string | null;
  metadata: Generated<Json>;
  notes: string | null;
  product_variant_id: string;
  quantity: Numeric;
  reason_id: string | null;
  serial_id: string | null;
  store_id: string;
  unit_cost: Numeric | null;
  updated_at: Timestamp | null;
}

export interface OperationalInventoryAdjustmentReasons {
  category: Generated<OperationalInventoryAdjustmentReasonCategory>;
  code: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  metadata: Generated<Json>;
  name: string;
  normalized_name: string;
  store_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalInventoryAdjustments {
  adjustment_number: string | null;
  approved_at: Timestamp | null;
  approved_by_store_member_id: string | null;
  cancelled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  kind: Generated<OperationalInventoryAdjustmentKind>;
  metadata: Generated<Json>;
  notes: string | null;
  occurred_at: Generated<Timestamp>;
  posted_at: Timestamp | null;
  posted_by_store_member_id: string | null;
  source_id: string | null;
  source_type: string | null;
  status: Generated<OperationalInventoryAdjustmentStatus>;
  store_id: string;
  submitted_at: Timestamp | null;
  updated_at: Timestamp | null;
}

export interface OperationalInventoryItems {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_movement_at: Timestamp | null;
  location_id: string;
  metadata: Generated<Json>;
  on_hand_qty: Generated<Numeric>;
  product_variant_id: string;
  reserved_qty: Generated<Numeric>;
  store_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalInventoryLotItems {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_movement_at: Timestamp | null;
  location_id: string;
  lot_id: string;
  metadata: Generated<Json>;
  on_hand_qty: Generated<Numeric>;
  product_variant_id: string;
  store_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalInventoryLotMovements {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  lot_id: string;
  movement_id: string;
  quantity: Numeric;
  store_id: string;
}

export interface OperationalInventoryLots {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  expires_at: Timestamp | null;
  id: Generated<string>;
  lot_code: string;
  manufactured_at: Timestamp | null;
  metadata: Generated<Json>;
  product_variant_id: string;
  store_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalInventoryMovements {
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  direction: OperationalInventoryMovementDirection;
  entered_quantity: Numeric | null;
  entered_uom_id: string | null;
  id: Generated<string>;
  is_reversal: Generated<boolean>;
  location_id: string;
  metadata: Generated<Json>;
  movement_type: OperationalInventoryMovementType;
  notes: string | null;
  occurred_at: Generated<Timestamp>;
  product_variant_id: string;
  quantity: Numeric;
  reversed_movement_id: string | null;
  source_id: string | null;
  source_type: string | null;
  store_id: string;
}

export interface OperationalInventorySerialMovements {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  movement_id: string;
  serial_id: string;
  status_after: OperationalInventorySerialStatus;
  status_before: OperationalInventorySerialStatus | null;
  store_id: string;
}

export interface OperationalInventorySerials {
  created_at: Generated<Timestamp>;
  damaged_at: Timestamp | null;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  location_id: string | null;
  metadata: Generated<Json>;
  product_variant_id: string;
  returned_at: Timestamp | null;
  serial_number: string;
  sold_at: Timestamp | null;
  status: Generated<OperationalInventorySerialStatus>;
  store_id: string;
  updated_at: Timestamp | null;
  written_off_at: Timestamp | null;
}

export interface OperationalInventoryStocktakeLines {
  counted_qty: Numeric | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  expected_qty: Numeric | null;
  id: Generated<string>;
  location_id: string;
  metadata: Generated<Json>;
  notes: string | null;
  product_variant_id: string;
  stocktake_id: string;
  store_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalInventoryStocktakes {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  location_id: string | null;
  metadata: Generated<Json>;
  notes: string | null;
  started_at: Timestamp | null;
  status: Generated<OperationalStocktakeStatus>;
  store_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalInventoryTransferLines {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  from_location_id: string;
  id: Generated<string>;
  lot_id: string | null;
  metadata: Generated<Json>;
  product_variant_id: string;
  quantity: Numeric;
  serial_id: string | null;
  store_id: string;
  to_location_id: string;
  transfer_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalInventoryTransfers {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  notes: string | null;
  status: Generated<OperationalInventoryTransferStatus>;
  store_id: string;
  submitted_at: Timestamp | null;
  updated_at: Timestamp | null;
}

export interface OperationalMediaAssets {
  checksum: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  file_size_bytes: Int8 | null;
  height: number | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  mime_type: string;
  storage_key: string;
  storage_provider: string;
  store_id: string;
  url: string;
  width: number | null;
}

export interface OperationalNotificationDeliveries {
  attempts: Generated<number>;
  channel: Generated<OperationalNotificationChannel>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  destination: string | null;
  id: Generated<string>;
  last_error: string | null;
  last_error_at: Timestamp | null;
  next_attempt_at: Timestamp | null;
  notification_id: string;
  payload: Generated<Json>;
  provider_name: string | null;
  provider_ref: string | null;
  sent_at: Timestamp | null;
  status: Generated<OperationalNotificationDeliveryStatus>;
  store_id: string;
  store_member_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalNotificationReceipts {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  delivered_at: Generated<Timestamp>;
  dismissed_at: Timestamp | null;
  id: Generated<string>;
  is_read: Generated<boolean>;
  notification_id: string;
  read_at: Timestamp | null;
  store_id: string;
  store_member_id: string;
}

export interface OperationalNotifications {
  action_url: string | null;
  audience_type: Generated<OperationalNotificationAudienceType>;
  body: string;
  channels: Generated<ArrayType<OperationalNotificationChannel>>;
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  deleted_at: Timestamp | null;
  event_type: string;
  failed_at: Timestamp | null;
  failure_reason: string | null;
  fanned_out_at: Timestamp | null;
  id: Generated<string>;
  payload: Generated<Json>;
  recipient_member_ids: string[] | null;
  recipient_roles: string[] | null;
  recipient_store_member_id: string | null;
  sent_at: Timestamp | null;
  source_id: string | null;
  source_type: string | null;
  status: Generated<OperationalNotificationStatus>;
  store_id: string;
  title: string;
  updated_at: Timestamp | null;
}

export interface OperationalOutboxEvents {
  aggregate_id: string | null;
  aggregate_type: string | null;
  causation_id: string | null;
  correlation_id: string | null;
  created_at: Generated<Timestamp>;
  destination: Generated<OperationalOutboxDestination>;
  event_type: string;
  id: Generated<string>;
  last_error: string | null;
  last_error_at: Timestamp | null;
  lock_expires_at: Timestamp | null;
  locked_at: Timestamp | null;
  locked_by: string | null;
  next_attempt_at: Timestamp | null;
  occurred_at: Generated<Timestamp>;
  partition_key: string | null;
  payload: Json;
  publish_attempts: Generated<number>;
  publish_ref: string | null;
  published_at: Timestamp | null;
  schema_version: Generated<number>;
  status: Generated<OperationalOutboxEventStatus>;
  store_id: string | null;
  trace_id: string | null;
  updated_at: Timestamp | null;
}

export interface OperationalPosPaymentIntents {
  amount: Numeric;
  amount_tendered: Numeric | null;
  change_given: Numeric | null;
  confirmed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  currency_code: string;
  deleted_at: Timestamp | null;
  failure_reason: string | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  method: Generated<OperationalPosPaymentMethod>;
  original_intent_id: string | null;
  reference_text: string | null;
  split_breakdown: Generated<Json>;
  status: Generated<OperationalPosPaymentIntentStatus>;
  store_id: string;
  transaction_id: string;
  type: Generated<OperationalPosPaymentIntentType>;
  updated_at: Timestamp | null;
}

export interface OperationalPosSessions {
  cash_over_short_amount: Numeric | null;
  closed_at: Timestamp | null;
  closing_cash_amount: Numeric | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  expected_cash_amount: Numeric | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  notes: string | null;
  opened_at: Generated<Timestamp>;
  opened_by_store_member_id: string;
  opening_cash_amount: Numeric | null;
  status: Generated<OperationalPosSessionStatus>;
  store_id: string;
  terminal_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalPosTerminals {
  app_version: string | null;
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  deleted_at: Timestamp | null;
  device_fingerprint: string;
  device_name: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  last_seen_at: Timestamp | null;
  metadata: Generated<Json>;
  platform: string | null;
  store_id: string;
  terminal_code: string;
  updated_at: Timestamp | null;
}

export interface OperationalPosTransactionLines {
  barcode_snapshot: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  discount_amount: Generated<Numeric>;
  discount_id: string | null;
  entered_quantity: Numeric | null;
  entered_uom_id: string | null;
  id: Generated<string>;
  line_subtotal: Numeric;
  line_total: Generated<Numeric>;
  metadata: Generated<Json>;
  product_name_snapshot: string;
  product_variant_id: string;
  quantity: Numeric;
  sku_snapshot: string | null;
  store_id: string;
  tax_amount: Generated<Numeric>;
  transaction_id: string;
  unit_price: Numeric;
  updated_at: Timestamp | null;
}

export interface OperationalPosTransactions {
  attendant_store_member_id: string;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  currency_code: string;
  customer_name: string | null;
  customer_phone: string | null;
  deleted_at: Timestamp | null;
  discount_amount: Generated<Numeric>;
  discount_id: string | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  notes: string | null;
  opened_at: Generated<Timestamp>;
  original_transaction_id: string | null;
  payment_intent_id: string | null;
  receipt_number: string | null;
  rounding_adjustment_amount: Generated<Numeric>;
  session_id: string;
  status: Generated<OperationalPosTransactionStatus>;
  store_id: string;
  subtotal_amount: Generated<Numeric>;
  tax_amount: Generated<Numeric>;
  terminal_id: string;
  total_amount: Generated<Numeric>;
  type: Generated<OperationalPosTransactionType>;
  updated_at: Timestamp | null;
  voided_at: Timestamp | null;
}

export interface OperationalProductMedia {
  alt_text: string | null;
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  is_primary: Generated<boolean>;
  media_asset_id: string;
  metadata: Generated<Json>;
  product_id: string;
  sort_order: number | null;
  store_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalProducts {
  attributes: Generated<Json>;
  base_uom_id: string | null;
  brand_name: string | null;
  category_id: string | null;
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  deleted_at: Timestamp | null;
  description: string | null;
  has_variants: Generated<boolean>;
  height_mm: Numeric | null;
  id: Generated<string>;
  is_perishable: Generated<boolean>;
  length_mm: Numeric | null;
  metadata: Generated<Json>;
  name: string;
  normalized_brand_name: string | null;
  normalized_name: string;
  preferred_supplier_id: string | null;
  product_type: Generated<OperationalProductType>;
  quantity_mode: Generated<OperationalQuantityMode>;
  requires_lot_tracking: Generated<boolean>;
  requires_serial_tracking: Generated<boolean>;
  search_vector: string | null;
  shelf_life_days: number | null;
  status: Generated<OperationalProductStatus>;
  store_id: string;
  tax_class_id: string | null;
  track_inventory: Generated<boolean>;
  updated_at: Timestamp | null;
  weight_grams: Numeric | null;
  width_mm: Numeric | null;
}

export interface OperationalProductUoms {
  conversion_to_base: Numeric;
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  is_default_for_purchase: Generated<boolean>;
  is_default_for_sales: Generated<boolean>;
  metadata: Generated<Json>;
  product_id: string;
  store_id: string;
  uom_id: string;
  updated_at: Timestamp | null;
  usage: Generated<OperationalProductUomUsage>;
}

export interface OperationalProductVariantOptionAssignments {
  created_at: Generated<Timestamp>;
  product_variant_id: string;
  store_id: string;
  store_variant_option_id: string;
}

export interface OperationalProductVariants {
  allow_discount: Generated<boolean>;
  allow_negative_inventory: Generated<boolean>;
  attributes: Generated<Json>;
  auto_update_cost: Generated<boolean>;
  barcode: string | null;
  barcode_registry_id: string | null;
  cost_price: Numeric | null;
  cost_updated_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  deleted_at: Timestamp | null;
  display_name: string;
  id: Generated<string>;
  is_active: Generated<boolean>;
  max_discount_percent: Numeric | null;
  metadata: Generated<Json>;
  min_selling_price: Numeric | null;
  normalized_display_name: string;
  pack_size: string | null;
  product_id: string;
  reorder_point: Numeric | null;
  reorder_quantity: Numeric | null;
  selling_price: Numeric;
  sku: string | null;
  sort_order: number | null;
  stock_valuation_method: Generated<OperationalStockValuationMethod>;
  store_id: string;
  unit_precision: Generated<number>;
  updated_at: Timestamp | null;
}

export interface OperationalPurchaseOrderLines {
  barcode_snapshot: string | null;
  close_reason: string | null;
  closed_at: Timestamp | null;
  closed_by_store_member_id: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  discount_amount: Generated<Numeric>;
  entered_ordered_qty: Numeric | null;
  entered_uom_id: string | null;
  id: Generated<string>;
  is_closed: Generated<boolean>;
  line_subtotal: Numeric;
  line_total: Numeric;
  metadata: Generated<Json>;
  notes: string | null;
  ordered_qty: Numeric;
  product_name_snapshot: string;
  product_variant_id: string;
  purchase_order_id: string;
  received_qty: Generated<Numeric>;
  sku_snapshot: string | null;
  store_id: string;
  tax_amount: Generated<Numeric>;
  unit_cost: Numeric;
  updated_at: Timestamp | null;
}

export interface OperationalPurchaseOrders {
  approved_at: Timestamp | null;
  approved_by_store_member_id: string | null;
  cancelled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  currency_code: string;
  deleted_at: Timestamp | null;
  discount_amount: Generated<Numeric>;
  expected_delivery_at: Timestamp | null;
  first_receipt_at: Timestamp | null;
  fully_received_at: Timestamp | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  notes: string | null;
  ordered_at: Timestamp | null;
  po_number: string | null;
  sent_at: Timestamp | null;
  shipping_amount: Generated<Numeric>;
  status: Generated<OperationalPurchaseOrderStatus>;
  store_id: string;
  submitted_at: Timestamp | null;
  subtotal_amount: Generated<Numeric>;
  supplier_id: string | null;
  tax_amount: Generated<Numeric>;
  total_amount: Generated<Numeric>;
  updated_at: Timestamp | null;
}

export interface OperationalPurchaseReceiptLines {
  barcode_snapshot: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  discount_amount: Generated<Numeric>;
  entered_received_qty: Numeric | null;
  entered_uom_id: string | null;
  id: Generated<string>;
  line_subtotal: Numeric;
  line_total: Numeric;
  location_id: string | null;
  lot_id: string | null;
  metadata: Generated<Json>;
  notes: string | null;
  product_name_snapshot: string;
  product_variant_id: string;
  purchase_order_line_id: string | null;
  purchase_receipt_id: string;
  received_qty: Numeric;
  serial_id: string | null;
  sku_snapshot: string | null;
  store_id: string;
  tax_amount: Generated<Numeric>;
  unit_cost: Numeric;
  updated_at: Timestamp | null;
}

export interface OperationalPurchaseReceipts {
  cancelled_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  currency_code: string;
  deleted_at: Timestamp | null;
  discount_amount: Generated<Numeric>;
  id: Generated<string>;
  location_id: string;
  metadata: Generated<Json>;
  notes: string | null;
  posted_at: Timestamp | null;
  posted_by_store_member_id: string | null;
  purchase_order_id: string | null;
  receipt_number: string | null;
  received_at: Generated<Timestamp>;
  shipping_amount: Generated<Numeric>;
  status: Generated<OperationalPurchaseReceiptStatus>;
  store_id: string;
  subtotal_amount: Generated<Numeric>;
  supplier_id: string | null;
  tax_amount: Generated<Numeric>;
  total_amount: Generated<Numeric>;
  updated_at: Timestamp | null;
}

export interface OperationalReportDefinitions {
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  deleted_at: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  is_shared: Generated<boolean>;
  name: string;
  parameters: Generated<Json>;
  report_key: string;
  scope: Generated<OperationalReportScope>;
  store_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalReportRuns {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  deleted_at: Timestamp | null;
  error_message: string | null;
  id: Generated<string>;
  output_format: Generated<OperationalReportOutputFormat>;
  output_media_id: string | null;
  parameters_snapshot: Generated<Json>;
  report_definition_id: string | null;
  report_key: string;
  scope: Generated<OperationalReportScope>;
  started_at: Timestamp | null;
  status: Generated<OperationalReportRunStatus>;
  store_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalStoreCategories {
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  deleted_at: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  metadata: Generated<Json>;
  name: string;
  normalized_name: string;
  parent_category_id: string | null;
  path: string;
  sort_order: number | null;
  store_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalStoreDiscountConditions {
  condition_group: Generated<number>;
  condition_type: OperationalDiscountConditionType;
  created_at: Generated<Timestamp>;
  discount_id: string;
  id: Generated<string>;
  numeric_value: Numeric | null;
  store_id: string;
  text_value: string | null;
  uuid_value: string | null;
}

export interface OperationalStoreDiscounts {
  code: string;
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  deleted_at: Timestamp | null;
  description: string | null;
  discount_type: OperationalDiscountType;
  id: Generated<string>;
  is_active: Generated<boolean>;
  max_uses: number | null;
  max_uses_per_transaction: number | null;
  metadata: Generated<Json>;
  name: string;
  normalized_name: string;
  requires_approval: Generated<boolean>;
  scope: Generated<OperationalDiscountScope>;
  store_id: string;
  updated_at: Timestamp | null;
  uses_count: Generated<number>;
  valid_from: Timestamp | null;
  valid_to: Timestamp | null;
  value: Numeric;
}

export interface OperationalStoreInvitations {
  accepted_at: Timestamp | null;
  accepted_by_user_id: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  email: string;
  expires_at: Timestamp;
  id: Generated<string>;
  invited_by_store_member_id: string | null;
  metadata: Generated<Json>;
  role: OperationalStoreRole;
  status: Generated<OperationalStoreInvitationStatus>;
  store_id: string;
  token_hash: string;
  updated_at: Timestamp | null;
}

export interface OperationalStoreLocations {
  code: string;
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  location_type: Generated<OperationalLocationType>;
  metadata: Generated<Json>;
  name: string;
  normalized_name: string;
  parent_location_id: string | null;
  path: string;
  sort_order: number | null;
  store_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalStoreMembers {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  last_pin_login_at: Timestamp | null;
  last_pin_login_ip: string | null;
  notification_preferences: Generated<Json>;
  permission_overrides: Generated<Json>;
  pin_hash: string | null;
  pin_set_at: Timestamp | null;
  role: OperationalStoreRole;
  status: Generated<OperationalStoreMemberStatus>;
  store_id: string;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface OperationalStoreNumberSequences {
  created_at: Generated<Timestamp>;
  current_value: Generated<Int8>;
  id: Generated<string>;
  include_day: Generated<boolean>;
  include_month: Generated<boolean>;
  include_year: Generated<boolean>;
  is_active: Generated<boolean>;
  last_reset_at: Timestamp | null;
  padding: Generated<number>;
  prefix: string | null;
  reset_policy: Generated<OperationalSequenceResetPolicy>;
  scope: Generated<OperationalSequenceScope>;
  separator: Generated<string>;
  sequence_key: string;
  store_id: string;
  suffix: string | null;
  updated_at: Timestamp | null;
}

export interface OperationalStoreOrderTaxRates {
  base: Generated<OperationalTaxBase>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  effective_from: Timestamp | null;
  effective_to: Timestamp | null;
  sort_order: number | null;
  store_id: string;
  tax_rate_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalStoreReceiptSettings {
  created_at: Generated<Timestamp>;
  footer_lines: string[] | null;
  header_lines: string[] | null;
  receipt_extra: Generated<Json>;
  receipt_title: string;
  show_attendant_name: Generated<boolean>;
  show_discounts: Generated<boolean>;
  show_store_address: Generated<boolean>;
  show_store_email: Generated<boolean>;
  show_store_phone: Generated<boolean>;
  show_tax_breakdown: Generated<boolean>;
  show_terminal_code: Generated<boolean>;
  store_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalStores {
  address_extra: Json | null;
  address_line_1: string;
  address_line_2: string | null;
  business_id: string;
  city: string;
  code: string;
  country_code: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  email: string | null;
  geo_location: string | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  name: string;
  phone: string | null;
  postal_code: string | null;
  state: string;
  status: Generated<OperationalStoreStatus>;
  updated_at: Timestamp | null;
}

export interface OperationalStoreSettings {
  allow_discount: Generated<boolean>;
  allow_negative_inventory: Generated<boolean>;
  auto_reorder_enabled: Generated<boolean>;
  cash_rounding_increment: Numeric | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  currency_symbol: Generated<string | null>;
  default_location_id: string | null;
  locale: Generated<string>;
  low_stock_threshold: Generated<number>;
  max_discount_percent: Generated<Numeric>;
  money_scale: Generated<number>;
  require_manager_for_price_override: Generated<boolean>;
  require_manager_for_refunds: Generated<boolean>;
  round_cash_totals: Generated<boolean>;
  settings_extra: Generated<Json>;
  stock_valuation_method: Generated<OperationalStockValuationMethod>;
  store_id: string;
  timezone: Generated<string>;
  updated_at: Timestamp | null;
}

export interface OperationalStoreSuppliers {
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  country_code: string | null;
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  deleted_at: Timestamp | null;
  email: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  metadata: Generated<Json>;
  name: string;
  normalized_name: string;
  notes: string | null;
  phone: string | null;
  postal_code: string | null;
  state: string | null;
  store_id: string;
  tax_id: string | null;
  updated_at: Timestamp | null;
}

export interface OperationalStoreUoms {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  metadata: Generated<Json>;
  name: string;
  normalized_name: string;
  sort_order: number | null;
  store_id: string;
  symbol: string | null;
  updated_at: Timestamp | null;
}

export interface OperationalStoreVariantGroups {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  name: string;
  normalized_name: string;
  store_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalStoreVariantOptions {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  metadata: Generated<Json>;
  name: string;
  normalized_name: string;
  store_id: string;
  store_variant_group_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalSupplierReturnLines {
  barcode_snapshot: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  discount_amount: Generated<Numeric>;
  entered_return_qty: Numeric | null;
  entered_uom_id: string | null;
  id: Generated<string>;
  line_subtotal: Numeric;
  line_total: Numeric;
  lot_id: string | null;
  metadata: Generated<Json>;
  notes: string | null;
  product_name_snapshot: string;
  product_variant_id: string;
  purchase_order_line_id: string | null;
  return_qty: Numeric;
  serial_id: string | null;
  sku_snapshot: string | null;
  store_id: string;
  supplier_return_id: string;
  tax_amount: Generated<Numeric>;
  unit_cost: Numeric;
  updated_at: Timestamp | null;
}

export interface OperationalSupplierReturns {
  approved_at: Timestamp | null;
  approved_by_store_member_id: string | null;
  cancelled_at: Timestamp | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by_store_member_id: string | null;
  currency_code: string;
  deleted_at: Timestamp | null;
  discount_amount: Generated<Numeric>;
  id: Generated<string>;
  metadata: Generated<Json>;
  notes: string | null;
  purchase_receipt_id: string | null;
  reason: string | null;
  return_number: string | null;
  shipped_at: Timestamp | null;
  shipping_amount: Generated<Numeric>;
  staging_transfer_id: string | null;
  status: Generated<OperationalSupplierReturnStatus>;
  store_id: string;
  submitted_at: Timestamp | null;
  subtotal_amount: Generated<Numeric>;
  supplier_id: string | null;
  tax_amount: Generated<Numeric>;
  total_amount: Generated<Numeric>;
  updated_at: Timestamp | null;
}

export interface OperationalTaxClasses {
  code: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  metadata: Generated<Json>;
  name: string;
  normalized_name: string;
  store_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalTaxClassRates {
  base: Generated<OperationalTaxBase>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  effective_from: Timestamp | null;
  effective_to: Timestamp | null;
  sort_order: number | null;
  store_id: string;
  tax_class_id: string;
  tax_rate_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalTaxRates {
  code: string;
  country_code: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  metadata: Generated<Json>;
  name: string;
  normalized_name: string;
  rate: Numeric;
  scope: Generated<OperationalTaxScope>;
  store_id: string;
  updated_at: Timestamp | null;
}

export interface OperationalUsers {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  display_name: string | null;
  email: string;
  email_verified_at: Timestamp | null;
  first_name: string | null;
  id: Generated<string>;
  last_name: string | null;
  password_hash: string;
  phone: string | null;
  phone_verified_at: Timestamp | null;
  status: Generated<OperationalUserStatus>;
  updated_at: Timestamp | null;
}

export interface OperationalUserSecurity {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  failed_login_attempts: Generated<number>;
  last_login_attempted_at: Timestamp | null;
  last_password_change_at: Timestamp | null;
  lockout_reason: string | null;
  lockout_until: Timestamp | null;
  mfa_enabled: Generated<boolean>;
  mfa_enabled_at: Timestamp | null;
  mfa_last_used_at: Timestamp | null;
  mfa_secret_ciphertext: Buffer | null;
  mfa_secret_kid: string | null;
  mfa_type: OperationalMfaType | null;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface PgStatStatements {
  calls: Int8 | null;
  dbid: number | null;
  jit_deform_count: Int8 | null;
  jit_deform_time: number | null;
  jit_emission_count: Int8 | null;
  jit_emission_time: number | null;
  jit_functions: Int8 | null;
  jit_generation_time: number | null;
  jit_inlining_count: Int8 | null;
  jit_inlining_time: number | null;
  jit_optimization_count: Int8 | null;
  jit_optimization_time: number | null;
  local_blk_read_time: number | null;
  local_blk_write_time: number | null;
  local_blks_dirtied: Int8 | null;
  local_blks_hit: Int8 | null;
  local_blks_read: Int8 | null;
  local_blks_written: Int8 | null;
  max_exec_time: number | null;
  max_plan_time: number | null;
  mean_exec_time: number | null;
  mean_plan_time: number | null;
  min_exec_time: number | null;
  min_plan_time: number | null;
  minmax_stats_since: Timestamp | null;
  parallel_workers_launched: Int8 | null;
  parallel_workers_to_launch: Int8 | null;
  plans: Int8 | null;
  query: string | null;
  queryid: Int8 | null;
  rows: Int8 | null;
  shared_blk_read_time: number | null;
  shared_blk_write_time: number | null;
  shared_blks_dirtied: Int8 | null;
  shared_blks_hit: Int8 | null;
  shared_blks_read: Int8 | null;
  shared_blks_written: Int8 | null;
  stats_since: Timestamp | null;
  stddev_exec_time: number | null;
  stddev_plan_time: number | null;
  temp_blk_read_time: number | null;
  temp_blk_write_time: number | null;
  temp_blks_read: Int8 | null;
  temp_blks_written: Int8 | null;
  toplevel: boolean | null;
  total_exec_time: number | null;
  total_plan_time: number | null;
  userid: number | null;
  wal_buffers_full: Int8 | null;
  wal_bytes: Numeric | null;
  wal_fpi: Int8 | null;
  wal_records: Int8 | null;
}

export interface PgStatStatementsInfo {
  dealloc: Int8 | null;
  stats_reset: Timestamp | null;
}

export interface SpatialRefSys {
  auth_name: string | null;
  auth_srid: number | null;
  proj4text: string | null;
  srid: number;
  srtext: string | null;
}

export interface TigerAddr {
  arid: string | null;
  fromarmid: number | null;
  fromhn: string | null;
  fromtyp: string | null;
  gid: Generated<number>;
  mtfcc: string | null;
  plus4: string | null;
  side: string | null;
  statefp: string | null;
  tlid: Int8 | null;
  toarmid: number | null;
  tohn: string | null;
  totyp: string | null;
  zip: string | null;
}

export interface TigerAddrfeat {
  aridl: string | null;
  aridr: string | null;
  edge_mtfcc: string | null;
  fullname: string | null;
  gid: Generated<number>;
  lfromhn: string | null;
  lfromtyp: string | null;
  linearid: string | null;
  ltohn: string | null;
  ltotyp: string | null;
  offsetl: string | null;
  offsetr: string | null;
  parityl: string | null;
  parityr: string | null;
  plus4l: string | null;
  plus4r: string | null;
  rfromhn: string | null;
  rfromtyp: string | null;
  rtohn: string | null;
  rtotyp: string | null;
  statefp: string;
  the_geom: string | null;
  tlid: Int8 | null;
  zipl: string | null;
  zipr: string | null;
}

export interface TigerBg {
  aland: number | null;
  awater: number | null;
  bg_id: string;
  blkgrpce: string | null;
  countyfp: string | null;
  funcstat: string | null;
  gid: Generated<number>;
  intptlat: string | null;
  intptlon: string | null;
  mtfcc: string | null;
  namelsad: string | null;
  statefp: string | null;
  the_geom: string | null;
  tractce: string | null;
}

export interface TigerCounty {
  aland: Int8 | null;
  awater: number | null;
  cbsafp: string | null;
  classfp: string | null;
  cntyidfp: string;
  countyfp: string | null;
  countyns: string | null;
  csafp: string | null;
  funcstat: string | null;
  gid: Generated<number>;
  intptlat: string | null;
  intptlon: string | null;
  lsad: string | null;
  metdivfp: string | null;
  mtfcc: string | null;
  name: string | null;
  namelsad: string | null;
  statefp: string | null;
  the_geom: string | null;
}

export interface TigerCountyLookup {
  co_code: number;
  name: string | null;
  st_code: number;
  state: string | null;
}

export interface TigerCountysubLookup {
  co_code: number;
  county: string | null;
  cs_code: number;
  name: string | null;
  st_code: number;
  state: string | null;
}

export interface TigerCousub {
  aland: Numeric | null;
  awater: Numeric | null;
  classfp: string | null;
  cnectafp: string | null;
  cosbidfp: string;
  countyfp: string | null;
  cousubfp: string | null;
  cousubns: string | null;
  funcstat: string | null;
  gid: Generated<number>;
  intptlat: string | null;
  intptlon: string | null;
  lsad: string | null;
  mtfcc: string | null;
  name: string | null;
  namelsad: string | null;
  nctadvfp: string | null;
  nectafp: string | null;
  statefp: string | null;
  the_geom: string | null;
}

export interface TigerDirectionLookup {
  abbrev: string | null;
  name: string;
}

export interface TigerEdges {
  artpath: string | null;
  countyfp: string | null;
  deckedroad: string | null;
  divroad: string | null;
  exttyp: string | null;
  featcat: string | null;
  fullname: string | null;
  gcseflg: string | null;
  gid: Generated<number>;
  hydroflg: string | null;
  lfromadd: string | null;
  ltoadd: string | null;
  mtfcc: string | null;
  offsetl: string | null;
  offsetr: string | null;
  olfflg: string | null;
  passflg: string | null;
  persist: string | null;
  railflg: string | null;
  rfromadd: string | null;
  roadflg: string | null;
  rtoadd: string | null;
  smid: string | null;
  statefp: string | null;
  tfidl: Numeric | null;
  tfidr: Numeric | null;
  the_geom: string | null;
  tlid: Int8 | null;
  tnidf: Numeric | null;
  tnidt: Numeric | null;
  ttyp: string | null;
  zipl: string | null;
  zipr: string | null;
}

export interface TigerFaces {
  aiannhce: string | null;
  aiannhce00: string | null;
  aiannhfp: string | null;
  aiannhfp00: string | null;
  anrcfp: string | null;
  anrcfp00: string | null;
  atotal: number | null;
  blkgrpce: string | null;
  blkgrpce00: string | null;
  blkgrpce20: string | null;
  blockce: string | null;
  blockce00: string | null;
  blockce20: string | null;
  cbsafp: string | null;
  cd108fp: string | null;
  cd111fp: string | null;
  cnectafp: string | null;
  comptyp: string | null;
  comptyp00: string | null;
  conctyfp: string | null;
  conctyfp00: string | null;
  countyfp: string | null;
  countyfp00: string | null;
  countyfp20: string | null;
  cousubfp: string | null;
  cousubfp00: string | null;
  csafp: string | null;
  elsdlea: string | null;
  elsdlea00: string | null;
  gid: Generated<number>;
  intptlat: string | null;
  intptlon: string | null;
  lwflag: string | null;
  metdivfp: string | null;
  nctadvfp: string | null;
  nectafp: string | null;
  offset: string | null;
  placefp: string | null;
  placefp00: string | null;
  puma5ce: string | null;
  puma5ce00: string | null;
  scsdlea: string | null;
  scsdlea00: string | null;
  sldlst: string | null;
  sldlst00: string | null;
  sldust: string | null;
  sldust00: string | null;
  statefp: string | null;
  statefp00: string | null;
  statefp20: string | null;
  submcdfp: string | null;
  submcdfp00: string | null;
  tazce: string | null;
  tazce00: string | null;
  tblkgpce: string | null;
  tfid: Numeric | null;
  the_geom: string | null;
  tractce: string | null;
  tractce00: string | null;
  tractce20: string | null;
  trsubce: string | null;
  trsubce00: string | null;
  trsubfp: string | null;
  trsubfp00: string | null;
  ttractce: string | null;
  uace: string | null;
  uace00: string | null;
  ugace: string | null;
  ugace00: string | null;
  unsdlea: string | null;
  unsdlea00: string | null;
  vtdst: string | null;
  vtdst00: string | null;
  zcta5ce: string | null;
  zcta5ce00: string | null;
}

export interface TigerFeatnames {
  fullname: string | null;
  gid: Generated<number>;
  linearid: string | null;
  mtfcc: string | null;
  name: string | null;
  paflag: string | null;
  predir: string | null;
  predirabrv: string | null;
  prequal: string | null;
  prequalabr: string | null;
  pretyp: string | null;
  pretypabrv: string | null;
  statefp: string | null;
  sufdir: string | null;
  sufdirabrv: string | null;
  sufqual: string | null;
  sufqualabr: string | null;
  suftyp: string | null;
  suftypabrv: string | null;
  tlid: Int8 | null;
}

export interface TigerGeocodeSettings {
  category: string | null;
  name: string;
  setting: string | null;
  short_desc: string | null;
  unit: string | null;
}

export interface TigerGeocodeSettingsDefault {
  category: string | null;
  name: string;
  setting: string | null;
  short_desc: string | null;
  unit: string | null;
}

export interface TigerLoaderLookuptables {
  /**
   * List of columns to exclude as an array. This is excluded from both input table and output table and rest of columns remaining are assumed to be in same order in both tables. gid, geoid,cpi,suffix1ce are excluded if no columns are specified.
   */
  columns_exclude: string[] | null;
  insert_mode: Generated<string>;
  level_county: Generated<boolean>;
  /**
   * These are tables that contain all data for the whole US so there is just a single file
   */
  level_nation: Generated<boolean>;
  level_state: Generated<boolean>;
  /**
   * Whether or not to load the table.  For states and zcta5 (you may just want to download states10, zcta510 nationwide file manually) load your own into a single table that inherits from tiger.states, tiger.zcta5.  You'll get improved performance for some geocoding cases.
   */
  load: Generated<boolean>;
  /**
   * This is the table name to inherit from and suffix of resulting output table -- how the table will be named --  edges here would mean -- ma_edges , pa_edges etc. except in the case of national tables. national level tables have no prefix
   */
  lookup_name: string;
  post_load_process: string | null;
  pre_load_process: string | null;
  process_order: Generated<number>;
  single_geom_mode: Generated<boolean | null>;
  single_mode: Generated<boolean>;
  /**
   * suffix of the tables to load e.g.  edges would load all tables like *edges.dbf(shp)  -- so tl_2010_42129_edges.dbf .
   */
  table_name: string | null;
  /**
   * Path to use for wget instead of that specified in year table.  Needed currently for zcta where they release that only for 2000 and 2010
   */
  website_root_override: string | null;
}

export interface TigerLoaderPlatform {
  county_process_command: string | null;
  declare_sect: string | null;
  environ_set_command: string | null;
  loader: string | null;
  os: string;
  path_sep: string | null;
  pgbin: string | null;
  psql: string | null;
  unzip_command: string | null;
  wget: string | null;
}

export interface TigerLoaderVariables {
  data_schema: string | null;
  staging_fold: string | null;
  staging_schema: string | null;
  tiger_year: string;
  website_root: string | null;
}

export interface TigerPagcGaz {
  id: Generated<number>;
  is_custom: Generated<boolean>;
  seq: number | null;
  stdword: string | null;
  token: number | null;
  word: string | null;
}

export interface TigerPagcLex {
  id: Generated<number>;
  is_custom: Generated<boolean>;
  seq: number | null;
  stdword: string | null;
  token: number | null;
  word: string | null;
}

export interface TigerPagcRules {
  id: Generated<number>;
  is_custom: Generated<boolean | null>;
  rule: string | null;
}

export interface TigerPlace {
  aland: Int8 | null;
  awater: Int8 | null;
  classfp: string | null;
  cpi: string | null;
  funcstat: string | null;
  gid: Generated<number>;
  intptlat: string | null;
  intptlon: string | null;
  lsad: string | null;
  mtfcc: string | null;
  name: string | null;
  namelsad: string | null;
  pcicbsa: string | null;
  pcinecta: string | null;
  placefp: string | null;
  placens: string | null;
  plcidfp: string;
  statefp: string | null;
  the_geom: string | null;
}

export interface TigerPlaceLookup {
  name: string | null;
  pl_code: number;
  st_code: number;
  state: string | null;
}

export interface TigerSecondaryUnitLookup {
  abbrev: string | null;
  name: string;
}

export interface TigerState {
  aland: Int8 | null;
  awater: Int8 | null;
  division: string | null;
  funcstat: string | null;
  gid: Generated<number>;
  intptlat: string | null;
  intptlon: string | null;
  lsad: string | null;
  mtfcc: string | null;
  name: string | null;
  region: string | null;
  statefp: string;
  statens: string | null;
  stusps: string;
  the_geom: string | null;
}

export interface TigerStateLookup {
  abbrev: string | null;
  name: string | null;
  st_code: number;
  statefp: string | null;
}

export interface TigerStreetTypeLookup {
  abbrev: string | null;
  is_hw: Generated<boolean>;
  name: string;
}

export interface TigerTabblock {
  aland: number | null;
  awater: number | null;
  blockce: string | null;
  countyfp: string | null;
  funcstat: string | null;
  gid: Generated<number>;
  intptlat: string | null;
  intptlon: string | null;
  mtfcc: string | null;
  name: string | null;
  statefp: string | null;
  tabblock_id: string;
  the_geom: string | null;
  tractce: string | null;
  uace: string | null;
  ur: string | null;
}

export interface TigerTabblock20 {
  aland: number | null;
  awater: number | null;
  blockce: string | null;
  countyfp: string | null;
  funcstat: string | null;
  geoid: string;
  housing: number | null;
  intptlat: string | null;
  intptlon: string | null;
  mtfcc: string | null;
  name: string | null;
  pop: number | null;
  statefp: string | null;
  the_geom: string | null;
  tractce: string | null;
  uace: string | null;
  uatype: string | null;
  ur: string | null;
}

export interface TigerTract {
  aland: number | null;
  awater: number | null;
  countyfp: string | null;
  funcstat: string | null;
  gid: Generated<number>;
  intptlat: string | null;
  intptlon: string | null;
  mtfcc: string | null;
  name: string | null;
  namelsad: string | null;
  statefp: string | null;
  the_geom: string | null;
  tract_id: string;
  tractce: string | null;
}

export interface TigerZcta5 {
  aland: number | null;
  awater: number | null;
  classfp: string | null;
  funcstat: string | null;
  gid: Generated<number>;
  intptlat: string | null;
  intptlon: string | null;
  mtfcc: string | null;
  partflg: string | null;
  statefp: string;
  the_geom: string | null;
  zcta5ce: string;
}

export interface TigerZipLookup {
  cnt: number | null;
  co_code: number | null;
  county: string | null;
  cousub: string | null;
  cs_code: number | null;
  pl_code: number | null;
  place: string | null;
  st_code: number | null;
  state: string | null;
  zip: number;
}

export interface TigerZipLookupAll {
  cnt: number | null;
  co_code: number | null;
  county: string | null;
  cousub: string | null;
  cs_code: number | null;
  pl_code: number | null;
  place: string | null;
  st_code: number | null;
  state: string | null;
  zip: number | null;
}

export interface TigerZipLookupBase {
  city: string | null;
  county: string | null;
  state: string | null;
  statefp: string | null;
  zip: string;
}

export interface TigerZipState {
  statefp: string | null;
  stusps: string;
  zip: string;
}

export interface TigerZipStateLoc {
  place: string;
  statefp: string | null;
  stusps: string;
  zip: string;
}

export interface TopologyLayer {
  child_id: number | null;
  feature_column: string;
  feature_type: number;
  layer_id: number;
  level: Generated<number>;
  schema_name: string;
  table_name: string;
  topology_id: number;
}

export interface TopologyTopology {
  hasz: Generated<boolean>;
  id: Generated<number>;
  name: string;
  precision: number;
  srid: number;
  useslargeids: Generated<boolean>;
}

export interface DB {
  'analytics.fact_sales': AnalyticsFactSales;
  'analytics.inventory_recommendations': AnalyticsInventoryRecommendations;
  'analytics.product_trend_snapshots': AnalyticsProductTrendSnapshots;
  geography_columns: GeographyColumns;
  geometry_columns: GeometryColumns;
  'operational.audit_logs': OperationalAuditLogs;
  'operational.barcode_registry': OperationalBarcodeRegistry;
  'operational.billing_customers': OperationalBillingCustomers;
  'operational.billing_invoices': OperationalBillingInvoices;
  'operational.billing_payment_methods': OperationalBillingPaymentMethods;
  'operational.billing_payments': OperationalBillingPayments;
  'operational.billing_plans': OperationalBillingPlans;
  'operational.billing_subscription_events': OperationalBillingSubscriptionEvents;
  'operational.billing_subscriptions': OperationalBillingSubscriptions;
  'operational.businesses': OperationalBusinesses;
  'operational.inventory_adjustment_lines': OperationalInventoryAdjustmentLines;
  'operational.inventory_adjustment_reasons': OperationalInventoryAdjustmentReasons;
  'operational.inventory_adjustments': OperationalInventoryAdjustments;
  'operational.inventory_items': OperationalInventoryItems;
  'operational.inventory_lot_items': OperationalInventoryLotItems;
  'operational.inventory_lot_movements': OperationalInventoryLotMovements;
  'operational.inventory_lots': OperationalInventoryLots;
  'operational.inventory_movements': OperationalInventoryMovements;
  'operational.inventory_serial_movements': OperationalInventorySerialMovements;
  'operational.inventory_serials': OperationalInventorySerials;
  'operational.inventory_stocktake_lines': OperationalInventoryStocktakeLines;
  'operational.inventory_stocktakes': OperationalInventoryStocktakes;
  'operational.inventory_transfer_lines': OperationalInventoryTransferLines;
  'operational.inventory_transfers': OperationalInventoryTransfers;
  'operational.media_assets': OperationalMediaAssets;
  'operational.notification_deliveries': OperationalNotificationDeliveries;
  'operational.notification_receipts': OperationalNotificationReceipts;
  'operational.notifications': OperationalNotifications;
  'operational.outbox_events': OperationalOutboxEvents;
  'operational.pos_payment_intents': OperationalPosPaymentIntents;
  'operational.pos_sessions': OperationalPosSessions;
  'operational.pos_terminals': OperationalPosTerminals;
  'operational.pos_transaction_lines': OperationalPosTransactionLines;
  'operational.pos_transactions': OperationalPosTransactions;
  'operational.product_media': OperationalProductMedia;
  'operational.product_uoms': OperationalProductUoms;
  'operational.product_variant_option_assignments': OperationalProductVariantOptionAssignments;
  'operational.product_variants': OperationalProductVariants;
  'operational.products': OperationalProducts;
  'operational.purchase_order_lines': OperationalPurchaseOrderLines;
  'operational.purchase_orders': OperationalPurchaseOrders;
  'operational.purchase_receipt_lines': OperationalPurchaseReceiptLines;
  'operational.purchase_receipts': OperationalPurchaseReceipts;
  'operational.report_definitions': OperationalReportDefinitions;
  'operational.report_runs': OperationalReportRuns;
  'operational.store_categories': OperationalStoreCategories;
  'operational.store_discount_conditions': OperationalStoreDiscountConditions;
  'operational.store_discounts': OperationalStoreDiscounts;
  'operational.store_invitations': OperationalStoreInvitations;
  'operational.store_locations': OperationalStoreLocations;
  'operational.store_members': OperationalStoreMembers;
  'operational.store_number_sequences': OperationalStoreNumberSequences;
  'operational.store_order_tax_rates': OperationalStoreOrderTaxRates;
  'operational.store_receipt_settings': OperationalStoreReceiptSettings;
  'operational.store_settings': OperationalStoreSettings;
  'operational.store_suppliers': OperationalStoreSuppliers;
  'operational.store_uoms': OperationalStoreUoms;
  'operational.store_variant_groups': OperationalStoreVariantGroups;
  'operational.store_variant_options': OperationalStoreVariantOptions;
  'operational.stores': OperationalStores;
  'operational.supplier_return_lines': OperationalSupplierReturnLines;
  'operational.supplier_returns': OperationalSupplierReturns;
  'operational.tax_class_rates': OperationalTaxClassRates;
  'operational.tax_classes': OperationalTaxClasses;
  'operational.tax_rates': OperationalTaxRates;
  'operational.user_security': OperationalUserSecurity;
  'operational.users': OperationalUsers;
  pg_stat_statements: PgStatStatements;
  pg_stat_statements_info: PgStatStatementsInfo;
  spatial_ref_sys: SpatialRefSys;
  'tiger.addr': TigerAddr;
  'tiger.addrfeat': TigerAddrfeat;
  'tiger.bg': TigerBg;
  'tiger.county': TigerCounty;
  'tiger.county_lookup': TigerCountyLookup;
  'tiger.countysub_lookup': TigerCountysubLookup;
  'tiger.cousub': TigerCousub;
  'tiger.direction_lookup': TigerDirectionLookup;
  'tiger.edges': TigerEdges;
  'tiger.faces': TigerFaces;
  'tiger.featnames': TigerFeatnames;
  'tiger.geocode_settings': TigerGeocodeSettings;
  'tiger.geocode_settings_default': TigerGeocodeSettingsDefault;
  'tiger.loader_lookuptables': TigerLoaderLookuptables;
  'tiger.loader_platform': TigerLoaderPlatform;
  'tiger.loader_variables': TigerLoaderVariables;
  'tiger.pagc_gaz': TigerPagcGaz;
  'tiger.pagc_lex': TigerPagcLex;
  'tiger.pagc_rules': TigerPagcRules;
  'tiger.place': TigerPlace;
  'tiger.place_lookup': TigerPlaceLookup;
  'tiger.secondary_unit_lookup': TigerSecondaryUnitLookup;
  'tiger.state': TigerState;
  'tiger.state_lookup': TigerStateLookup;
  'tiger.street_type_lookup': TigerStreetTypeLookup;
  'tiger.tabblock': TigerTabblock;
  'tiger.tabblock20': TigerTabblock20;
  'tiger.tract': TigerTract;
  'tiger.zcta5': TigerZcta5;
  'tiger.zip_lookup': TigerZipLookup;
  'tiger.zip_lookup_all': TigerZipLookupAll;
  'tiger.zip_lookup_base': TigerZipLookupBase;
  'tiger.zip_state': TigerZipState;
  'tiger.zip_state_loc': TigerZipStateLoc;
  'topology.layer': TopologyLayer;
  'topology.topology': TopologyTopology;
}
